### ISSUE TITLE
Modificar perfiles de otros Usuarios

### ISSUE THREAD

**Issue by Kiwi322** [Kiwi322/FISW#1]
Se debe solucionar el problema de que los usuarios puedan accedes a las cuentas de otros usuarios y modificar sus perfiles.

Ricardo: Debes revisar este problema y solucionarlo

**Comment by Ricardo-Gamboa-A** [comment]
Ya pueden acceder, falta que cada usuario pueda modificar su perfil unicamente,

**Comment by Kiwi322** [comment]
Problema fue solucionado, logrando las funcionlidades según requerimientos
