### ISSUE TITLE
Arreglos Entregable 2

### ISSUE THREAD

**Issue by alexballr** [Kiwi322/FISW#5]
- Agregar requerimiento: Registrar usuario
- Agregar requerimiento: Tutor de tesis y colaboradores
- Caso de uso Revisar reportes: offstage usuario?
- Tener todas las tablas
- Agregar Correo a Login

**Comment by Kiwi322** [comment]
Entregable II.
Efectuadas en Documento Entregable II:
    Agregar requerimiento: Registrar usuario.
    Agregar requerimiento: Tutor de tesis y colaboradores.
    Caso de uso Revisar reportes: offstage usuario.

Efectuadas en Software:
    Tener todas las tablas.
    Agregar Correo a Login.

**Comment by Kiwi322** [comment]
Se efectuaron correcciones efectuadas por ayudante en Entregable I.
